# Site wide configuration

title:            Data Portfolia
locale:           en_US
url:              https://verali0816.github.io
#url:              http://localhost:4000

name: Wenqian Li
description: My personal website
# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Site owner
owner:
  name: Wenqian Li
  avatar: https://scontent-ort2-2.xx.fbcdn.net/v/t1.0-9/10678696_515285735277239_125876959609987863_n.jpg?oh=3c60d795a57419c1530af2558b0b186e&oe=59F3C6C1
  bio: "Statistic student"
  email: veralimd@gmail.com
  
  
  facebook: #username
  google:
    plus: #username
    analytics: 
    verify: 
    ad-client: 
    ad-slot: 
  bing-verify: 
  github: verali0816
  stackoverflow: 
  linkedin: 
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
